spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/mysys?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password:

server:
  port: 8088